In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.datasets import load_diabetes

In [2]:
x,y = load_diabetes(return_X_y=True)

In [3]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
x.shape

(442, 10)

In [6]:
y.shape

(442,)

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=10)

In [8]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [9]:
y_pred = lr.predict(x_test)

In [10]:
r2_score(y_test,y_pred)

0.5341962544929233

In [11]:
lr.coef_

array([  -3.89155188, -225.62880027,  517.89525355,  328.32132183,
       -727.23345563,  410.96799392,   80.26601137,  218.18738355,
        704.2805541 ,   40.02247238])

In [12]:
lr.intercept_

152.2555053490769

In [20]:
class RGRegressor:
    
    def __init__(self,learning_rate=0.01,epochs=1000):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,x_train,y_train):
        
        #init your coefficient
        self.intercept_ = 0
        self.coef_ = np.ones(x_train.shape[1])
        
        for i in range(self.epochs):
            
            # update all coefficient and intercept
            
            y_hat = np.dot(x_train, self.coef_) + self.intercept_
            intercept_der = -2 * np.mean(y_train - y_hat)
            self.intercept_ = self.intercept_ - (self.lr * intercept_der)
            
            coef_der =  coef_der = -2 * np.dot((y_train - y_hat),x_train)/x_train.shape[0]
            self.coef_ = self.coef_ - (self.lr * coef_der)
            
        print(self.intercept_,self.coef_)
        
    def predict(self, x_test):
        
        return np.dot(x_test,self.coef_) + self.intercept_

In [52]:
gdr = RGRegressor(learning_rate = 0.7,epochs=10000)

gdr.fit(x_train,y_train)

152.1434125756941 [ 1.25616047e-02 -2.20568358e+02  5.27390109e+02  3.24294268e+02
 -2.03965230e+02  1.81682864e+00 -1.52505469e+02  1.47566705e+02
  5.03488112e+02  4.26703277e+01]


In [53]:
y_pred = gdr.predict(x_test)

In [54]:
r2_score(y_test,y_pred)

0.5305197485599656