In [3]:
from sklearn.datasets import make_classification
import numpy as np
x, y = make_classification(n_samples=100, n_features=2, n_informative=1,n_redundant=0,
                           n_classes=2, n_clusters_per_class=1, random_state=41,hypercube=False,class_sep=30)

In [5]:
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1])

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()

x_train = st.fit_transform(x_train)
x_test = st.fit_transform(x_test)

In [8]:
print(x_train)

[[-0.84932393 -1.53701299]
 [-1.07595264  1.12229565]
 [ 0.73372374  0.06930508]
 [-0.96769022 -0.41172367]
 [-1.20334492 -0.49616332]
 [ 1.1137427   0.80563928]
 [ 0.76760136  1.01277249]
 [ 1.06563038  0.20438   ]
 [-0.99783069  0.87978139]
 [ 0.70572408  0.15476635]
 [-0.83107705 -1.03838933]
 [ 0.76092546  0.87220534]
 [ 1.15801055  0.50451273]
 [ 1.13719738  0.49345125]
 [ 1.16841183  1.21781613]
 [ 0.73923277 -0.75842243]
 [-0.92243833  0.79603832]
 [-0.93361384  1.02739572]
 [-0.79073351  0.22258621]
 [ 0.75488646  1.70150219]
 [ 0.94676884  0.44845652]
 [-1.10449594 -0.87086428]
 [-0.92386953 -0.6697325 ]
 [-1.01627051  0.5575452 ]
 [-0.76286475  0.16390507]
 [ 1.19968866 -0.04587481]
 [ 0.78577869 -1.25016756]
 [ 0.88541448 -0.11988692]
 [ 1.00142447 -1.04959758]
 [-1.27450972 -0.55775653]
 [ 0.89225191 -0.62206996]
 [-1.07196862 -0.18699575]
 [ 0.71542913 -0.87103701]
 [ 1.34581241  0.489188  ]
 [-0.9550077   0.36785072]
 [-1.07145671 -0.935158  ]
 [ 1.2608138  -0.78705506]
 

In [9]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()

classifier.fit(x_train,y_train)

LogisticRegression()

In [10]:
y_pred = classifier.predict(x_test)

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[13  0]
 [ 0 12]]


In [12]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

1.0
